name: example
description: A sample project that show how to use dart_hooks command line script.
homepage: https://github.com/bitsydarel/dart_github_hooks
repository: https://github.com/bitsydarel/dart_github_hooks
issue_tracker: https://github.com/bitsydarel/dart_github_hooks/issues

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  flutter_code_style: ^2.0.1