name: vcshooks
description: A sample command-line application.
version: 0.1.0
homepage: https://github.com/bitsydarel/vcshooks
repository: https://github.com/bitsydarel/vcshooks
issue_tracker: https://github.com/bitsydarel/vcshooks/issues

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.7.0
  args: ^1.6.0
  http: ^0.12.2
  meta: ^1.2.4
  io: ^0.3.4

dev_dependencies:
  flutter_code_style: ^2.0.2
  test: ^1.15.7

executables:
  vcshooks: